---
- block:
  - name: Check '{{ item }}' installation status
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    check_mode: yes
    register: result
  - name: Fail if '{{ item }}' is not installed
    ansible.builtin.assert:
      that: result.changed is false
      success_msg: "Package '{{item}}' is installed!"
      fail_msg: "Package '{{ item }}' is not installed!"
