---
# Preflight checks
- ansible.builtin.import_tasks: utils/check-tinytex-installation.yml

# Installation
- ansible.builtin.include_tasks: utils/install-system-dependencies.yml
  when: install_check.state is undefined
- ansible.builtin.include_tasks: install-tinytex.yml
  when: install_check.state is undefined
