---
- name: Converge
  hosts: all
  roles:
    - role: dagos.tinytex
      vars:
        state: present
        packages:
          - adjustbox
    - role: dagos.tinytex
      vars:
        state: latest
        packages:
          - zref
