---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: tinytex-instance
    image: "docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # By testing present and latest states time is saved but idempotence is not testable
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
