---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if installation folder exists
      ansible.builtin.file:
        path: /opt/tinytex
        state: directory
        mode: 0777
      check_mode: true
      register: result
      failed_when: result.state != 'directory' or result.mode != '0777'

    - name: Check if installed binaries are on the path
      ansible.builtin.command: tlmgr --version
      changed_when: false
      register: result
      failed_when: "result.stdout_lines[1] != 'tlmgr using installation: /opt/tinytex'"

    - ansible.builtin.import_tasks: ../../tasks/utils/get-installed-tlmgr-packages.yml
    - name: Check if packages were installed correctly
      ansible.builtin.assert:
        that: "{{ installed_packages.stdout.find(item) >= 0 }}"
        fail_msg: "Installed packages: {{ installed_packages.stdout }}"
        quiet: true
      loop:
        - adjustbox # Provided via converge, role present
        - zref # Provided via converge, role latest
